title: "ソフトウェアエンジニアになろう【バックエンド編】"
summary: "本の紹介文"
topics: ["Ruby on Rails", "Ruby", "Docker"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - terminal
  - git
  - docker
  - database
  - ruby
  - vscode
  - rspec
  - fizzbuzz